import type { Metadata } from "next";
import { compounds } from "@/lib/compounds";
import { CoaArchive, type CoaRow } from "./coa-archive";

export const metadata: Metadata = {
  title: "Certificates of analysis — The Pure Pep",
  description:
    "Third-party Certificates of Analysis from ILS Laboratories, indexed by accession and lot number and verifiable directly with the lab.",
  alternates: { canonical: "/coa" },
};

/**
 * Rows for the archive.
 *
 * Only lots with a signed certificate on file appear. This page exists to
 * prove testing, so a row without a document behind it is worse than no
 * row — anyone asking for that lot's paperwork would find there is none.
 *
 * It previously also listed three fabricated "historical" lots per
 * compound, generated by decrementing the real lot number and shaving a
 * little off the purity to look plausible. Those are gone.
 */
function buildRows(): CoaRow[] {
  const rows: CoaRow[] = [];

  for (const c of compounds) {
    for (const variant of c.variants) {
      if (!variant.coaPdf) continue;

      rows.push({
        lot: variant.lot,
        compound: c.name,
        accession: c.accession,
        purity: `${(variant.purity ?? c.purity).toFixed(2)}%`,
        date: variant.coaDate.replaceAll("-", "."),
        lab: variant.lab ?? "—",
        pdf: `/coa/${variant.coaPdf}`,
      });
    }
  }

  // Sort newest-first by date string (YYYY.MM.DD sorts lexically correct).
  rows.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  return rows;
}

const GLOSSARY: Array<{ term: string; def: string }> = [
  {
    term: "Accession",
    def: "The Pure Pep internal compound identifier (e.g. PP-002). Stable across lots.",
  },
  {
    term: "Lot",
    def: "Batch identifier in the form A-NNNN. One synthesis run, one CoA.",
  },
  {
    term: "Theoretical MW",
    def: "Average molecular weight calculated from the published amino-acid sequence and modifications.",
  },
  {
    term: "Observed MW",
    def: "Mean of three ESI-MS measurements on the prepared lot. Reported to two decimals.",
  },
  {
    term: "Retention time",
    def: "Main-peak retention on the HPLC column under the published gradient. Used for identity confirmation across runs.",
  },
  {
    term: "Counterion",
    def: "Salt form the peptide is isolated as — usually TFA, sometimes acetate. Affects net peptide content.",
  },
  {
    term: "Net peptide content",
    def: "Mass of peptide backbone per mg of lyophilised material, after subtracting water + counterion.",
  },
  {
    term: "CoA date",
    def: "Date the independent laboratory completed the final assay and signed the PDF.",
  },
];

export default function CoaPage() {
  const rows = buildRows();

  return (
    <section className="relative border-b border-hairline">
      <div className="mx-auto w-full max-w-[var(--content-max)] pad-x section-y">
        {/* Hero */}
        <div className="max-w-3xl">
          <div
            className="flex items-center font-mono tracking-[0.3em] uppercase text-muted-foreground"
            style={{
              fontSize: "clamp(10px, 0.3vw + 9px, 11px)",
              gap: "clamp(0.75rem, 1.5vw, 1.25rem)",
            }}
          >
            <span className="whitespace-nowrap text-brand">§ 04</span>
            <span
              className="h-px shrink-0 bg-hairline"
              style={{ width: "clamp(1.5rem, 3vw, 2.75rem)" }}
            />
            <span>Documentation</span>
          </div>
          <h1
            className="font-display leading-[0.92] tracking-[-0.025em]"
            style={{
              marginTop: "clamp(1rem, 1.5vw, 1.5rem)",
              fontSize: "clamp(2.5rem, 7vw, 7rem)",
            }}
          >
            Certificates of{" "}
            <span className="italic text-gradient-brand">analysis.</span>
          </h1>
          <p
            className="mt-6 max-w-xl font-sans leading-relaxed text-muted-foreground"
            style={{ fontSize: "clamp(0.95rem, 0.4vw + 0.85rem, 1.125rem)" }}
          >
            Certificates issued by ILS Laboratories, indexed by accession and
            lot number. Each one is verifiable directly with the lab using the
            code printed on it. Lots still in assay are not listed here — if a
            lot has a certificate, it is on this page.
          </p>
        </div>

        {/* Archive */}
        <div
          className="mt-[clamp(3rem,5vw,5rem)] border-t border-hairline"
          style={{ paddingTop: "clamp(1.75rem, 2.5vw, 2.5rem)" }}
        >
          <div className="flex items-baseline justify-between gap-6">
            <div
              className="flex items-center font-mono tracking-[0.3em] uppercase text-muted-foreground"
              style={{
                fontSize: "clamp(10px, 0.3vw + 9px, 11px)",
                gap: "clamp(0.75rem, 1.5vw, 1.25rem)",
              }}
            >
              <span className="text-brand">§ 04.2</span>
              <span
                className="h-px shrink-0 bg-hairline"
                style={{ width: "clamp(1.5rem, 3vw, 2.75rem)" }}
              />
              <span>Archive</span>
            </div>
            <span
              className="font-mono tracking-[0.25em] uppercase text-muted-foreground"
              style={{ fontSize: "clamp(9px, 0.25vw + 8px, 10px)" }}
            >
              {rows.length} lots indexed
            </span>
          </div>

          <div className="mt-8">
            <CoaArchive rows={rows} />
          </div>
        </div>

        {/* Reading a CoA — glossary */}
        <div
          className="mt-[clamp(3rem,5vw,5rem)] border-t border-hairline"
          style={{ paddingTop: "clamp(1.75rem, 2.5vw, 2.5rem)" }}
        >
          <div className="flex items-baseline justify-between gap-6">
            <div
              className="flex items-center font-mono tracking-[0.3em] uppercase text-muted-foreground"
              style={{
                fontSize: "clamp(10px, 0.3vw + 9px, 11px)",
                gap: "clamp(0.75rem, 1.5vw, 1.25rem)",
              }}
            >
              <span className="text-brand">§ 04.3</span>
              <span
                className="h-px shrink-0 bg-hairline"
                style={{ width: "clamp(1.5rem, 3vw, 2.75rem)" }}
              />
              <span>Reading a CoA</span>
            </div>
          </div>

          <h2
            className="mt-4 max-w-2xl font-display leading-[1.02] tracking-tight"
            style={{ fontSize: "clamp(1.6rem, 3vw, 2.5rem)" }}
          >
            Every field on the page,{" "}
            <span className="italic text-gradient-brand">defined.</span>
          </h2>

          <dl className="mt-10 grid gap-px bg-hairline sm:grid-cols-2">
            {GLOSSARY.map((g) => (
              <div
                key={g.term}
                className="bg-background"
                style={{ padding: "clamp(1.1rem, 1.8vw, 1.5rem)" }}
              >
                <dt
                  className="font-mono tracking-[0.3em] uppercase text-brand"
                  style={{ fontSize: "clamp(9.5px, 0.25vw + 8.5px, 10.5px)" }}
                >
                  {g.term}
                </dt>
                <dd
                  className="mt-2 font-sans leading-relaxed text-foreground"
                  style={{ fontSize: "clamp(0.86rem, 0.25vw + 0.8rem, 0.95rem)" }}
                >
                  {g.def}
                </dd>
              </div>
            ))}
          </dl>
        </div>

        {/* Verification + labs */}
        <div
          className="mt-[clamp(3rem,5vw,5rem)] border-t border-hairline"
          style={{ paddingTop: "clamp(1.75rem, 2.5vw, 2.5rem)" }}
        >
          <div className="flex items-baseline justify-between gap-6">
            <div
              className="flex items-center font-mono tracking-[0.3em] uppercase text-muted-foreground"
              style={{
                fontSize: "clamp(10px, 0.3vw + 9px, 11px)",
                gap: "clamp(0.75rem, 1.5vw, 1.25rem)",
              }}
            >
              <span className="text-brand">§ 04.4</span>
              <span
                className="h-px shrink-0 bg-hairline"
                style={{ width: "clamp(1.5rem, 3vw, 2.75rem)" }}
              />
              <span>Verification &amp; chain of custody</span>
            </div>
          </div>

          <div className="mt-10 grid gap-px bg-hairline lg:grid-cols-3">
            <article
              className="flex flex-col gap-3 bg-background"
              style={{ padding: "clamp(1.25rem, 2vw, 1.75rem)" }}
            >
              <div
                className="font-mono tracking-[0.3em] uppercase text-brand"
                style={{ fontSize: "clamp(9.5px, 0.25vw + 8.5px, 10.5px)" }}
              >
                Issuing laboratory
              </div>
              <div
                className="font-display leading-[1.05]"
                style={{ fontSize: "clamp(1.3rem, 2vw, 1.75rem)" }}
              >
                ILS Laboratories
              </div>
              <p
                className="font-sans leading-relaxed text-muted-foreground"
                style={{ fontSize: "clamp(0.86rem, 0.25vw + 0.8rem, 0.95rem)" }}
              >
                8222 Vickers St, Suite 106, San Diego, CA 92111. ISO/IEC 17025 accredited. Every certificate listed here was issued and signed by ILS; we do not assay our own material.
              </p>
            </article>
            <article
              className="flex flex-col gap-3 bg-background"
              style={{ padding: "clamp(1.25rem, 2vw, 1.75rem)" }}
            >
              <div
                className="font-mono tracking-[0.3em] uppercase text-brand"
                style={{ fontSize: "clamp(9.5px, 0.25vw + 8.5px, 10.5px)" }}
              >
                How to verify
              </div>
              <div
                className="font-display leading-[1.05]"
                style={{ fontSize: "clamp(1.3rem, 2vw, 1.75rem)" }}
              >
                Direct with the lab
              </div>
              <p
                className="font-sans leading-relaxed text-muted-foreground"
                style={{ fontSize: "clamp(0.86rem, 0.25vw + 0.8rem, 0.95rem)" }}
              >
                Each certificate carries its own CoA number and a single-use access code, printed in the footer and encoded in the QR panel. Enter them at portal.ils-lab.com to confirm the document against the laboratory&rsquo;s own record — independently of us.
              </p>
            </article>
            <article
              className="flex flex-col gap-3 bg-background"
              style={{ padding: "clamp(1.25rem, 2vw, 1.75rem)" }}
            >
              <div
                className="font-mono tracking-[0.3em] uppercase text-brand"
                style={{ fontSize: "clamp(9.5px, 0.25vw + 8.5px, 10.5px)" }}
              >
                What is measured
              </div>
              <div
                className="font-display leading-[1.05]"
                style={{ fontSize: "clamp(1.3rem, 2vw, 1.75rem)" }}
              >
                HPLC, per lot
              </div>
              <p
                className="font-sans leading-relaxed text-muted-foreground"
                style={{ fontSize: "clamp(0.86rem, 0.25vw + 0.8rem, 0.95rem)" }}
              >
                Purity, identity and quantitation by RP-HPLC with UV area normalisation at 214 nm, plus a fentanyl immunoassay screen. Selected lots additionally carry endotoxin testing to USP &lt;85&gt;. The methods run are printed on each certificate.
              </p>
            </article>
          </div>
        </div>
      </div>
    </section>
  );
}
